# Name of driver used for accessing OpenTSDB API
#
# There are two currently available depending on the version of OpenTSDB :
# - v1.x: com.dassault_systemes.infra.hoptim.opentsdb.OpenTSDBDriverV1
#
# There exists also a Mock driver which simulated the API in memory :
# com.dassault_systemes.infra.hoptim.opentsdb.OpenTSDBDriverMock
driverClassName: com.dassault_systemes.infra.hoptim.opentsdb.OpenTSDBDriverMock

# URL of the OpenTSDB API in the cluster
apiUrl: http://localhost:4235/api/v1

# Name in HBase of the main TSDB table
tsdbTable: ec2-52-9-229-2.us-west-1.compute.amazonaws.com-tsdb
#tsdbTable: ec2-52-52-4-47.us-west-1.compute.amazonaws.com-tsdb

# Name in HBase of the UID TSDB table
tsdbUidTable: ec2-52-9-229-2.us-west-1.compute.amazonaws.com-tsdb-uid
#tsdbUidTable: ec2-52-52-4-47.us-west-1.compute.amazonaws.com-tsdb

# There is a maximum number of regions recommanded per region server.
# This settings between 0 and 1 tells how much regions we should allow for one region server (1 means we allow max).
regionServerFillFactor: 0.6

# This value is used to automatically launch an optimization when there is a minimum gain in the score
# This gain is a percentage (eg. 100 means the cluster gets double better score after optimization)
scoreGainThreshold: 10

# This value determines the sleeping time in seconds between two automatic repeatition of optimization algorithm
# eg. A value of 86400 means there is one repeatition per day
schedulerPeriod: 5

# This value determines the delay in seconds before first execution of scheduled optimization algorithm
# eg. A value of 3600 means one hour delay
schedulerDelay: 0

# VIP Metrics which need to be prioritized for splitting
# <metric_name>: <weight>
#
# The bigger the weight, the highest number of splits for this metric.
# The total of all the weights should be 1.
vipMetrics:
    paas.supervision.alert: 0.4
    a.vip.1: 0.15
    d.vip.2: 0.15
    g.vip.3: 0.15
    k.vip.4: 0.15

# The delay in secondes when executing delayed optimization tasks
delayedExecutionTime: 10
